version: '3.3'

services:
    frontend:
        build: ../2.8/example-frontend/
        container_name: frontend
        networks:
            - first-network
        
    backend:
        build: ../2.8/example-backend/
        container_name: backend
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db_backend
            - POSTGRES_PASSWORD=example
        depends_on:
            - db
        networks:
            - first-network
            
    redis:
        image: redis
        container_name: redis
        networks:
            - first-network
        
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=example
            - PGDATA=/var/lib/postgresql/data
        container_name: db_backend
        networks:
            - first-network
        volumes:
             - ./database:/var/lib/postgresql/data
        
    proxy:
        image: nginx
        container_name: proxy
        environment:
            - NGINX_HOST=http://localhost
            - NGINX_PORT=80
        volumes:
           # - ./templates:/etc/nginx/templates
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        networks:
            - first-network
        depends_on:
            - frontend
            - backend
            - redis
            
networks:
    first-network:
        name: nginx-network

# example-frontend and example-backend in the part_1/2.8/ repository. 
# sudo docker-compose up. Button  worked/turned green  were not working. Messages did not work.

