version: '3.3'

services:
    frontend:
        build: ./example-frontend/
        container_name: frontend
        networks:
            - first-network
        
    backend:
        build: ./example-backend/
        container_name: backend
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db_backend
            - POSTGRES_PASSWORD=example
        depends_on:
            - db
        networks:
            - first-network
            
    redis:
        image: redis
        container_name: redis
        networks:
            - first-network
        
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment: 
            POSTGRES_PASSWORD: example           
        container_name: db_backend
        networks:
            - first-network
        
    proxy:
        image: nginx
        container_name: proxy
        environment:
            - NGINX_HOST=http://localhost
            - NGINX_PORT=80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        networks:
            - first-network
        depends_on:
            - frontend
            - backend
            - redis
            
networks:
    first-network:
        name: nginx-network

# There are Dockerfiles also in each example, but they are not visible in Github (added to .gitignore or .dockerignore etc)
# sudo docker-compose up.

