version: '3.3'

services:
    frontend:
        build: ../../part_1/1.14/example-frontend/    
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
        ports:
            - 5000:5000
        
    backend:
        build: ../../part_1/1.14/example-backend/
        environment:
            - REQUEST_ORIGIN=http://localhost:5000
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=example
        ports:
            - 8080:8080
        depends_on:
            - db
            
    redis:
        image: redis
        
    db:
        image: postgres:13.2-alpine
        restart: always
        environment: 
            POSTGRES_PASSWORD: example           
        container_name: db_backend

# example-frontend and example-backend in the part_1/1.14/ repository. There are Dockerfiles also in each example, but they are not visible in Github (added to .gitignore or .dockerignore etc)
# sudo docker-compose up. Buttons 1.14, 2.4 and 2.6 worked/turned green. Messages worked.
