FROM node:14

EXPOSE 5000

WORKDIR /usr/src/front-app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN apt update
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt install -y nodejs
RUN npm install -g serve
RUN npm install
RUN npm run build

CMD ["serve", "-s", "-l", "5000", "build"]

#sudo docker build . -t frontend
#sudo docker run -it --rm -p 5000:5000 frontend
