FROM golang:1.16

EXPOSE 8080

WORKDIR /go/src/app
# recommended by docker hub page. Or /myownapp found on telegram
COPY . .

ENV PORT=8080 REQUEST_ORIGIN=http://localhost:5000

RUN go get -d -v ./...
RUN go install -v ./...
RUN go build
#RUN go test ./...

CMD ./server

#build and run from Docker hub
#$ sudo docker build -t backend .
#$ sudo docker run -it -p 8080:8080 --rm backend
